{
    "name": "Les Rapports  de paie",
    "version": "1.0",
    "depends": ['base','web','hr',"hr_payroll_ci", 'report_xlsx'],
    "author": "Veone Team",
    "category": "hr",
    "description": """
    This module provide :
    """,
    'data': [

        'data/sequence_disa.xml',
        'data/sequence_cnps_mensuel.xml',
        'data/sequence_cnps_trimestriel.xml',
        'data/sequence_dasc.xml',
        'data/report_templates.xml',
        "raports/payroll_raport.xml",
        "raports/report_fdfp.xml",
        "raports/report_hr_its.xml",
        "views/hr_rapport_menu.xml",
        "views/res_config_settings_views.xml",
        'wizard/HrPayrollView.xml',
        'views/HrSalaryRuleView.xml',
        'views/report_cnps_trimestriel.xml',
        'views/report_cnps_monthly.xml',
        'views/report_dasc.xml',
        'views/report_hr_disa.xml',
        'views/report_payroll.xml',
        'wizard/Hr_Dasc_wiew.xml',
        'wizard/hr_its_view.xml',
        #'wizard/HrCnpsMonthlyView.xml',
        #'wizard/HrCnpsTrimestrielView.xml',
        'wizard/hrPayrollDISAView.xml',
        'wizard/hrPayrollFDFPView.xml',

        'views/hr_payroll_analyse_view.xml',
        "data/report_paperformat.xml",
    ],
    'demo_xml': [],
    'installable': True,
    'active': False,
#    'certificate': 'certificate',
}